FROM ubuntu:17.10

# Setup python and java and base system
ENV DEBIAN_FRONTEND noninteractive
ENV LANG=en_US.UTF-8

RUN apt-get -q -y update && \
  apt-get upgrade -q -y && \
  apt-get install -q -y openjdk-8-jre-headless \
  libssl-dev \
    python2.7 python-pip python-pip \
    build-essential git-core openssl libffi6 libffi-dev curl \
    &&  apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#RUN pip install --upgrade pip


# Run updates, install basics and cleanup
# - build-essential: Compile specific dependencies
# - git-core: Checkout git repos
#RUN apt-get update -qq \
#    && apt-get install -y --no-install-recommends build-essential git-core openssl libssl-dev libffi6 libffi-dev curl \ 
#    &&  apt-get clean \
#    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*



# use bash always
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Default to UTF-8 file.encoding
ENV LANG C.UTF-8

# workdir
WORKDIR /app
COPY . /app
#COPY --from=0 /usr/lib/jvm /usr/lib/jvm

# rasa stack
## rasa nlu
RUN pip install -r requirements/requirements_docker.txt
## spacy models
RUN pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz --no-cache-dir > /dev/null \
    && python -m spacy link en_core_web_sm en

# python -m spacy.en.download all
RUN pip install duckling
RUN python -m spacy download en
#RUN python -m spacy download fr

## rasa core
RUN pip install rasa_core

# volumes
VOLUME ["/app/logs", "/app/data", "/app/config"]


EXPOSE 5000

ENTRYPOINT ["./entrypoint.sh"]
